<div id="reply-form" style="display: none">
    <?php echo $block->getChildHtml('adminhtml.block.improvedcontact.reply'); ?>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'Magento_Ui/js/modal/alert'
        ],
        function (
            $,
            modal,
            alert
        ) {
            var options = {
                type: 'slide',
                responsive: true,
                innerScroll: true,
                title: 'Reply on customer message',
                buttons: [{
                    text: $.mage.__('Reply'),
                    class: 'button primary',
                    click: function () {
                        disabled = $('#customer_email').removeAttr('disabled');
                        form = $(".modal-content #reply_form");
                        var form_data = form.serialize();
                        disabled.attr('disabled', 'disabled');
                        $.ajax({
                            url: "<?php  echo $block->getActionUrl()?>",
                            type: 'POST',
                            data: form_data,
                            showLoader: true,
                            success: function (result) {
                                $('body').loader('hide');
                                if (typeof result.error !== 'undefined' && result.error === 1) {
                                    alert({
                                        title: $.mage.__('Error happened'),
                                        content: result.message,
                                        actions: {
                                            always: function () {
                                            }
                                        }
                                    });
                                } else {
                                    $('button.action-close').last().click();
                                }
                            },
                            error: function (result) {
                                alert({
                                    title: $.mage.__('Real Error happened'),
                                    content: result.message,
                                    actions: {
                                        always: function () {
                                        }
                                    }
                                });
                            }
                        })
                    }
                }],
            };
            $('#reply').on('click', function () {
                modal(options, $('#reply-form'));
                $('#reply-form').modal('openModal');
            });
        }
    );

</script>
